version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      # sysctl -w vm.max_map_count=262144
      # docker-compose up -d es
      # docker-compose build test
      #- apt-get update -y
      #- apt-get install -y python-pip zip
      - pip install awscli
      - pip install pytest
      - pytest --version
      - python --version
      #- pip install boto3
  build:
    commands:
      - echo Entered the build phase...
      #- docker-compose run test python test_addition.py
      #- docker-compose run test python -m pytest -v
      - pytest -q test_addition.py
      #- zip -r static.zip .
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
      - test_addition.py
      #- static.zip
